### ISSUE TITLE
Input Data Generation

### ISSUE THREAD

**Issue by SURABHI-GUPTA** [nsalminen/HMDRemoval#1]
@nsalminen Great work ! Thanks for releasing the code.
How did you manage to generate the input data, along with HMD? Can you suggest? Is input data generation code available?

**Comment by nsalminen** [comment]
Thank you for your interest in our work @SURABHI-GUPTA!

The full data generation code is not yet available and I currently can't provide info on if/when it will be. In the meantime, I will describe the required steps so you could potentially reproduce the date generation pipeline:

1. Generate meshes of faces with the [scalismo-faces](https://github.com/unibas-gravis/scalismo-faces) framework.
2. Generate RGB-D images of the face meshes with [mesh2rgbd](https://github.com/nsalminen/mesh2rgbd).
3. Generate HMD masks. There's several options here, depending on your needs:
    - If you **don't** need support for different face poses/positions: manually create a binary image that resembles an HMD which could be used for every face.
    - If you **do** need support for different face poses/positions: download a mesh of an HMD and programmatically position it on the face in step two (you could use any specific vertex for this and place the HMD relative to it). Then render one RGB-D image of the face and one RGB-D image of the mask and repeat for each face.

I hope this gives you sufficient information for now. Feel free to use this issue for any further questions. I will post here when I have updates on the release of the full data generation code.

**Comment by GitZinger** [comment]
@nsalminen 
any chance you could release your full data generation code now? because that is a lot of work to implement instead of replicating....
thanks

**Comment by nsalminen** [comment]
Hi @GitZinger, thanks for your interest! I planned on making the full data generation pipeline available, but I have not had the time to do this properly yet. In case it's of any use for you, I will share the output data of the data generation pipeline with you that was used for training and testing [here](https://drive.google.com/drive/folders/1yUCjjtQ8uDKeeYZgC3CAy7Wcembkn_WH?usp=sharing).

This folder contains two .rar files:
- `allMasks.tar`   this contains image mask files, for all possible mask orientations.
- `bfm2017_40k_grey.tar`  this contains the training/validation/testing images including the .flist files. To use these, the paths in the .flist files should be modified to point to the correct directory in your setup (_find & replace_ would do the job).

Let me know if you have any questions, thanks!

**Comment by GitZinger** [comment]
> Hi @GitZinger, thanks for your interest! I planned on making the full data generation pipeline available, but I have not had the time to do this properly yet. In case it's of any use for you, I will share the output data of the data generation pipeline with you that was used for training and testing [here](https://drive.google.com/drive/folders/1yUCjjtQ8uDKeeYZgC3CAy7Wcembkn_WH?usp=sharing).
> 
> This folder contains two .rar files:
> 
> * `allMasks.tar`   this contains image mask files, for all possible mask orientations.
> * `bfm2017_40k_grey.tar`  this contains the training/validation/testing images including the .flist files. To use these, the paths in the .flist files should be modified to point to the correct directory in your setup (_find & replace_ would do the job).
> 
> Let me know if you have any questions, thanks!
The Train/input data, there is no mask on it. so during the invoking the` train.py`, the face and mask will be combined together as the input?

**Comment by nsalminen** [comment]
Hi @GitZinger, that's correct. The mask is applied to the image before it's fed to the network.
